name: 'Setup project'

description: 'Setup node, pnpm and install'

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2.2.4

    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install
      shell: bash
      run: pnpm install --frozen-lockfile
