name: 'Setup project'

description: 'Setup node, pnpm and install'

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 8

    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
        cache-dependency-path: './pnpm-lock.yaml'

    - name: Install
      shell: bash
      run: pnpm install --frozen-lockfile
