name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup-project

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup-project

      - name: Build
        env:
          TEAM: ${{ secrets.VERCEL_TEAM }}
          TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: pnpm exec turbo run build --api="https://api.vercel.com" --team="$TEAM" --token="$TOKEN"
