name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'pnpm'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          TEAM: ${{ secrets.VERCEL_TEAM }}
          TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: pnpm exec turbo run build --api="https://api.vercel.com" --team="$TEAM" --token="$TOKEN"
