name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

env:
  TURBO_TEAM: ${{ secrets.VERCEL_TEAM }}
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-project

      - name: Build
        run: pnpm exec turbo run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-project

      - name: Lint
        run: pnpm exec turbo run lint
