name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup-project

      - name: Build
        env:
          TURBO_TEAM: ${{ secrets.VERCEL_TEAM }}
          TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: pnpm exec turbo run build --api="https://api.vercel.com" --team="$TEAM" --token="$TOKEN"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup-project

      - name: Lint
        env:
          TEAM: ${{ secrets.VERCEL_TEAM }}
          TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: pnpm exec turbo run lint --api="https://api.vercel.com" --team="$TEAM" --token="$TOKEN"
