name: Renovate

on:
  schedule:
    - cron: '0/15 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v31.14.1
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
